### ISSUE TITLE
🎯 Draft Bitcoin Deepa Bot User Guide

### ISSUE THREAD

**Issue by HansiNR** [CeyLabs/BitcoinDeepa-TMA-Bot#16]
## Task

As a technical writer, I want to draft the Bitcoin Deepa Bot User Guide so that users can understand how to effectively use the bot.

## Acceptance Criteria

- [x] A draft version of the Bitcoin Deepa Bot User Guide is completed.
- [ ] The guide includes sections on installation, setup, and usage instructions.
- [ ] The guide is reviewed and approved by the project team.
- [ ]  Update the user guide as a Gitbook

## Assets

- Mockup: N/A

## EXTRA NOTES

- The guide should be easy to understand and include screenshots where applicable.

Draft of the bitcoin deepa userGuide 
https://docs.google.com/document/d/1-exMKAC5ArZyJtNxpWb6TbcFj5oL4lN_on0B_da3Law/edit
